### ISSUE TITLE
Unexpected token .

### ISSUE THREAD

**Issue by FRosner** [panosoft/elm-websocket-client#1]
Hi guys,

My elm app is compiling but when I open it I get:

![image](https://cloud.githubusercontent.com/assets/3427394/25222917/12bce2e4-25ba-11e7-80c4-c8af2815daaf.png)

**elm-package.json**

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        ".",
        "src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v <= 2.0.0",
        "panosoft/elm-websocket-client.git": "3.0.0 <= v < 3.0.1"
    },
    "dependency-sources": {
      "panosoft/elm-websocket-client": {
        "url": "https://github.com/panosoft/elm-websocket-client.git",
        "ref": "master"
      }
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

**Comment by FRosner** [comment]
Ah it is actually an issue of how I installed it with the ELM git installer. I removed the .git and now I at least get a different error.

What is the expected way of adding the project as a dependency (what URL, what ref)?

**Comment by cscalfani** [comment]
You have add it manually to your `elm-package.json`:

    "panosoft/elm-websocket-client.git": "3.0.0 <= v < 4.0.0"

Then you use `elm-github-install`.

What's the new error?

**Comment by FRosner** [comment]
The problem is if the project contains `.git`, it generates JS code with `.git` and throws up on the `.`. I fixed it by changing `https://github.com/panosoft/elm-websocket-client.git` to `https://github.com/panosoft/elm-websocket-client`

**Comment by FRosner** [comment]
The new error is #2
