### ISSUE TITLE
Relative WS URL not working when listening

### ISSUE THREAD

**Issue by FRosner** [panosoft/elm-websocket-client#3]
### Problem

When using absolute URLs for connecting and listening to a Websocket it works as expected. But when using relative URLs (which is the common use case as you don't know where your app is going to be deployed) it manages to establish the connection but you are not getting any messages. The messages arrive successfully however (which can be seen through the network inspector of Chrome).

```
Websocket.listen WsListenError WsMessage WsConnectionLost webSocketBaseUrl
Websocket.send WsSendError WsSent webSocketBaseUrl ( Encode.encode 0 wrappedMessage )
```

#### Absolute URL

```
webSocketBaseUrl = "ws://localhost:9000/ws"
```

<img width="297" alt="screen shot 2017-05-02 at 20 13 06" src="https://cloud.githubusercontent.com/assets/3427394/25633527/b46fdc2e-2f77-11e7-93df-fbbfe0054911.png">

#### Relative URL

```
webSocketBaseUrl = "/ws"
```

<img width="238" alt="screen shot 2017-05-02 at 20 13 43" src="https://cloud.githubusercontent.com/assets/3427394/25633537/bbe2d312-2f77-11e7-94d7-afa41ebb7856.png">

**Comment by cscalfani** [comment]
I'm pretty sure websocket URLs must be absolute.

**Comment by FRosner** [comment]
Thanks @cscalfani for that clarification. Can you tell me what I need to change in your library to make it work?

**Comment by FRosner** [comment]
I mean I can connect to it using a relative URL and I am receiving messages so the issue seems to be in the channel? 

http://stackoverflow.com/questions/16090530/how-to-point-a-websocket-to-the-current-server says the same but I don't want to use the location module just for this purpose. The fact that I am receiving messages and am able to connect makes me believe that there is a way.

**Comment by FRosner** [comment]
Sorry for wasting your time... I just found out that I did not specify the `connect` URL to be relative... Now it "works" as expected:

`ConnectError: ("/ws","Failed to construct 'WebSocket': The URL '/ws' is invalid.")`

**Comment by cscalfani** [comment]
Glad you figured it out.

**Comment by FRosner** [comment]
Only for future reference, this is how I solved it. I hope it'll not backfire or something...

https://github.com/FRosner/cluster-broccoli/commit/847fd818ecd8c30ffedd6144885378f9c0d46a3f
