### ISSUE TITLE
Understand reason why websocket connection failed

### ISSUE THREAD

**Issue by FRosner** [panosoft/elm-websocket-client#4]
### Problem

I would like to understand why the websocket connection failed. I have an application server that might reject my connection if I am not authorized to establish it. It will return a response with status code 403. However I struggle to process the error I get from elm-websocket-client through the Elm channel. This is because of two reasons:

1. It is a string and not a typed error. Is there a way to get the underlying error in a typed way instead of having to parse the string (which might even change without me noticing)?
2. The error I get is the same for a failed connection because the server is offline and the server returned 403. Is that because 403 is the wrong status code to use? I tried a different status code but it doesn't matter, I'm always getting the same error. How can I understand why the connection failed so that I can distinguish the two cases (server offline, authorization problem)?

<img width="1423" alt="screen shot 2017-05-04 at 18 35 14" src="https://cloud.githubusercontent.com/assets/3427394/25715353/84f498d8-30fb-11e7-96ec-6b73b05c9892.png">

### Links

- http://stackoverflow.com/questions/19304157/getting-the-reason-why-websockets-closed
- http://stackoverflow.com/questions/40047813/is-it-possible-to-check-for-websocket-403-responses
- https://github.com/panosoft/elm-websocket-client/blob/master/src/Native/Websocket.js#L85

**Comment by FRosner** [comment]
So I assume there is no way to get more information on why the websocket was not opened in the first place for "security reasons"? If you don't have any other idea to tackle this we can close this issue :( Sorry for wasting your time :D

**Comment by cscalfani** [comment]
Having error codes is a good idea. So, I've released version 4.0.0 which now returns a Tuple of `(ConnectErrorCode, ErrorMessage)`.

Codes can be found in the [Websocket Protocol](https://tools.ietf.org/html/rfc6455#section-7.4.1).

**Comment by FRosner** [comment]
Thanks! :) AFAIK these codes refer only to successfully connected websockets which are then closed. If the websocket cannot be connected, you will always get 1006.

**Comment by cscalfani** [comment]
That's too bad. Oh, well. `ConnectionClosedTagger` now has error code and message like the original `ConnectErrorTagger`. Version 5.0.0.

Maybe that will contain better information if and when it happens. My testing only showed 1006.
