### ISSUE TITLE
Native module vs using Websocket.LowLevel

### ISSUE THREAD

**Issue by FRosner** [panosoft/elm-websocket-client#5]
Hi @cscalfani,

just out of curiosity (sorry for creating an issue for that but I couldn't find you on gitter), why did you decide to write a native module? Is it possible to accomplish the same functionality using [`WebSocket.LowLevel`](http://package.elm-lang.org/packages/elm-lang/websocket/1.0.2/WebSocket-LowLevel) instead of native JS?

**Comment by cscalfani** [comment]
It's in the first 2 paragraphs of `readme.md`.

**Comment by FRosner** [comment]
Ok I've read

> Websocket Effects Manager for Elm that works with BOTH front-end (browser) and back-end (node) programs. It allows for more sophisticated higher-level protocols than the default Websocket provided by Elm. It provides a message when the connection is lost allowing clients to employ their own reconnection strategy.

>For example, when connecting to stateful back-end services, the client may need to re-authenticate or re-subscribe to that service.

But can't you accomplish this with WebSocket.LowLevel? It has `onMessage` and `onClose` handlers. What is missing there?

**Comment by cscalfani** [comment]
First, it works in the browser AND node.

Second, according to the docs,`send` queues message that fail to send. Or at least that's the idea that I got from the docs on `bytesQueued` which is in the same interface. But looking at the code, it appears that it's not the case.

So I would say that you might be able to get by with using the low level interface. But it would only work in a browser (without some hacking ala HTTP in node) which is fine for most people but we're writing Full Stack Elm. In fact, I mostly write Backend Elm.

The biggest reason was that I had written other Effects Managers and I just went to what I knew and I didn't know much about Elm when I made that decision so my ability to understand the standard library was limited.

**Comment by FRosner** [comment]
Makes sense. Thanks for the explanation!

I so far used it only for the front-end of one of my projects and I am still in the migration from Angular. I didn't have much time to dedicate so it was more a side project most of the time but now I'm putting more effort and that's why I'm spamming you 😄
